-- Seed authoritative medical reference knowledge into rag_documents and rag_chunks
-- Sources: NIH MedlinePlus, CDC, WHO, American Diabetes Association, American Heart Association

-- 1. Insert Trusted RAG Documents
INSERT INTO rag_documents (id, title, organization, url, publication_date, category, content) VALUES
('a0000001-0000-0000-0000-000000000001', 'Complete Blood Count (CBC) Patient Reference', 'National Institutes of Health (NIH) - MedlinePlus', 'https://medlineplus.gov/lab-tests/complete-blood-count/', '2024-01-15', 'Hematology',
'The Complete Blood Count (CBC) measures several components of blood: Red Blood Cells (RBCs carry oxygen), White Blood Cells (WBCs fight infection), Platelets (aid blood clotting), Hemoglobin (oxygen-carrying protein in RBCs), and Hematocrit (ratio of RBC volume to total blood volume). Low hemoglobin or hematocrit indicates anemia, which may cause fatigue, pale skin, or shortness of breath. High WBC counts frequently point to infections, inflammatory conditions, or physical stress. Low platelet counts (thrombocytopenia) can cause increased bruising or bleeding risks. High platelet counts (thrombocytosis) may occur in response to acute inflammation or bone marrow conditions.'),

('a0000002-0000-0000-0000-000000000002', 'Lipid Panel: Understanding Cholesterol and Triglycerides', 'American Heart Association (AHA) & CDC', 'https://www.cdc.gov/cholesterol/about.html', '2024-02-01', 'Cardiovascular & Lipidology',
'A lipid panel measures lipids in the bloodstream: Total Cholesterol, Low-Density Lipoprotein (LDL) cholesterol, High-Density Lipoprotein (HDL) cholesterol, and Triglycerides. LDL cholesterol is often termed "bad cholesterol" because elevated levels can lead to plaque buildup in arteries (atherosclerosis), increasing long-term cardiovascular risk. HDL cholesterol is termed "good cholesterol" as it helps remove excess cholesterol from arteries back to the liver for excretion. Elevated triglycerides are often associated with metabolic syndrome, insulin resistance, dietary excess of refined sugars, or alcohol intake.'),

('a0000003-0000-0000-0000-000000000003', 'Comprehensive Metabolic Panel: Liver Function Tests (LFT)', 'National Institutes of Health (NIH) - MedlinePlus', 'https://medlineplus.gov/lab-tests/liver-function-tests/', '2024-01-20', 'Hepatology',
'Liver Function Tests measure key enzymes and proteins: Alanine Transaminase (ALT), Aspartate Transaminase (AST), Alkaline Phosphatase (ALP), Total Bilirubin, and Albumin. Elevated ALT and AST levels typically suggest hepatocellular irritation or injury, commonly seen in fatty liver disease, medication effects, alcohol use, or viral hepatitis. Alkaline Phosphatase (ALP) and Bilirubin elevations may indicate biliary tract congestion or bone turnover. Low albumin levels may suggest chronic liver impairment, nutritional deficits, or kidney protein loss.'),

('a0000004-0000-0000-0000-000000000004', 'Kidney Function Tests: Creatinine, BUN, and eGFR', 'National Kidney Foundation (NKF) & CDC', 'https://www.kidney.org/atoz/content/understanding-your-lab-values', '2024-02-10', 'Nephrology',
'Kidney function is assessed primarily using Serum Creatinine, Blood Urea Nitrogen (BUN), and estimated Glomerular Filtration Rate (eGFR). Creatinine is a waste product generated from muscle breakdown filtered exclusively by healthy kidneys. Elevated serum creatinine and lower eGFR indicate reduced kidney filtration capacity. Temporary elevations can occur with severe dehydration, high protein intake, strenuous exercise, or certain medications (e.g., NSAIDs). Persistent reduction in eGFR requires medical review to evaluate chronic kidney health.'),

('a0000005-0000-0000-0000-000000000005', 'Thyroid Stimulating Hormone (TSH) and Free T4', 'American Thyroid Association (ATA)', 'https://www.thyroid.org/thyroid-function-tests/', '2024-01-10', 'Endocrinology',
'Thyroid testing evaluates the pituitary gland hormone Thyroid Stimulating Hormone (TSH) and thyroid hormones (Free T4 and Free T3). Elevated TSH with normal or low Free T4 typically suggests an underactive thyroid (hypothyroidism), which can lead to symptoms like lethargy, cold intolerance, dry skin, and weight gain. Low TSH with elevated Free T4 typically suggests an overactive thyroid (hyperthyroidism), associated with palpitations, heat intolerance, tremor, and unexplained weight loss.'),

('a0000006-0000-0000-0000-000000000006', 'Blood Glucose, Fasting Plasma Glucose, and HbA1c', 'American Diabetes Association (ADA)', 'https://diabetes.org/about-diabetes/diagnosis', '2024-01-05', 'Metabolism & Diabetes',
'Fasting blood glucose measures blood sugar levels after an overnight fast. Normal fasting glucose is typically under 100 mg/dL. Fasting glucose between 100 and 125 mg/dL suggests impaired fasting glucose (prediabetes), while fasting glucose of 126 mg/dL or higher on more than one test is diagnostic of diabetes. Glycated hemoglobin (HbA1c) reflects average blood sugar levels over the preceding 2 to 3 months. An HbA1c below 5.7% is normal; 5.7% to 6.4% indicates prediabetes; 6.5% or above indicates diabetes.'),

('a0000007-0000-0000-0000-000000000007', 'Urinalysis: Complete Urine Examination', 'National Institutes of Health (NIH) - MedlinePlus', 'https://medlineplus.gov/lab-tests/urinalysis/', '2024-01-25', 'Urology & Nephrology',
'A routine urinalysis checks visual, chemical, and microscopic properties of urine. Key parameters include Protein, Glucose, Leukocyte Esterase, Nitrites, Red Blood Cells (RBCs), and White Blood Cells (WBCs). Presence of leukocyte esterase and nitrites often indicates a urinary tract infection (UTI). Significant urinary protein (proteinuria) warrants investigation for kidney filtration issues. Trace blood in urine (hematuria) requires medical assessment to rule out infection, kidney stones, or other urinary tract causes.')
ON CONFLICT (id) DO NOTHING;

-- 2. Insert Knowledge Chunks
INSERT INTO rag_chunks (id, document_id, chunk_index, parameter_name, content, metadata) VALUES
('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001', 1, 'Hemoglobin',
'Hemoglobin is the iron-containing protein in red blood cells that transports oxygen from the lungs to the body tissues. Low hemoglobin indicates anemia, which may be caused by nutritional deficiencies (iron, vitamin B12, folate), chronic blood loss, or bone marrow disorders. Symptoms can include fatigue, dizziness, and pallor.', '{"source": "NIH MedlinePlus", "parameter": "Hemoglobin", "urgency_context": "Moderate anemia requires doctor visit; very low (<7 g/dL) is critical"}'::jsonb),

('b0000002-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001', 2, 'White Blood Cell Count',
'White Blood Cells (WBC or Leukocytes) are essential components of the immune defense. Elevated WBC count (leukocytosis) is most commonly an expected physiological reaction to bacterial or viral infections, inflammatory conditions, tissue injury, or severe stress. Moderately low WBC counts may be seen in viral illnesses or autoimmune conditions.', '{"source": "NIH MedlinePlus", "parameter": "WBC", "urgency_context": "Severe elevation >25,000 or severe drop <2,000 requires urgent doctor review"}'::jsonb),

('b0000003-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001', 3, 'Platelet Count',
'Platelets (thrombocytes) are tiny blood cells that help blood clot and seal cuts or vascular damage. A low platelet count (thrombocytopenia) can cause unexplained bruising, petechiae, or prolonged bleeding. High platelets (thrombocytosis) can occur reactively after acute blood loss, iron deficiency, or chronic inflammation.', '{"source": "NIH MedlinePlus", "parameter": "Platelets", "urgency_context": "Counts below 50,000 /uL increase bleeding risk and require prompt evaluation"}'::jsonb),

('b0000004-0000-0000-0000-000000000002', 'a0000002-0000-0000-0000-000000000002', 1, 'LDL Cholesterol',
'Low-Density Lipoprotein (LDL) cholesterol carries cholesterol through the bloodstream. Elevated LDL levels can build up inside artery walls forming plaques that narrow arteries (atherosclerosis). For general cardiovascular prevention, lifestyle measures like a heart-healthy diet, regular physical activity, and weight management are first-line, and a physician may discuss lipid-lowering therapy depending on total cardiovascular risk.', '{"source": "CDC & AHA", "parameter": "LDL Cholesterol", "urgency_context": "Elevated LDL is a chronic risk factor requiring routine discussion with doctor"}'::jsonb),

('b0000005-0000-0000-0000-000000000002', 'a0000002-0000-0000-0000-000000000002', 2, 'Triglycerides',
'Triglycerides are the most common type of fat in the body, derived from calories not immediately used. Elevated triglycerides are often linked to higher intake of carbohydrates, sugars, alcohol, or insulin resistance. Extremely high triglycerides (>500 mg/dL) carry a potential risk of acute pancreatitis and require medical attention.', '{"source": "CDC & AHA", "parameter": "Triglycerides", "urgency_context": "Very high (>500 mg/dL) requires prompt medical consultation"}'::jsonb),

('b0000006-0000-0000-0000-000000000003', 'a0000003-0000-0000-0000-000000000003', 1, 'ALT and AST',
'Alanine Aminotransferase (ALT) and Aspartate Aminotransferase (AST) are enzymes primarily concentrated in liver cells. When liver cells are irritated or damaged, these enzymes leak into the circulation. Mild to moderate elevations are frequently caused by nonalcoholic fatty liver disease (NAFLD), medications, or alcohol, while dramatic elevations (over 10x upper limit) may indicate acute liver inflammation.', '{"source": "NIH MedlinePlus", "parameter": "ALT/AST", "urgency_context": "Mild elevation warrants routine follow-up; marked elevation warrants prompt evaluation"}'::jsonb),

('b0000007-0000-0000-0000-000000000004', 'a0000004-0000-0000-0000-000000000004', 1, 'Creatinine',
'Creatinine is a waste byproduct of muscular metabolism excreted by the kidneys. Higher serum creatinine levels indicate diminished kidney clearance. Acute factors such as severe dehydration, extreme exertion, or certain drugs can temporarily elevate creatinine. A doctor will typically assess creatinine alongside eGFR and urine protein to distinguish acute vs chronic changes.', '{"source": "National Kidney Foundation", "parameter": "Creatinine", "urgency_context": "Marked acute rise warrants prompt medical review"}'::jsonb),

('b0000008-0000-0000-0000-000000000005', 'a0000005-0000-0000-0000-000000000005', 1, 'TSH (Thyroid Stimulating Hormone)',
'TSH is secreted by the pituitary gland to regulate thyroid hormone production. A high TSH signifies that the pituitary is stimulating the thyroid because thyroid hormone output is insufficient (hypothyroidism). A low TSH signifies excess thyroid hormone circulating in the body (hyperthyroidism). Physicians usually check Free T4 before concluding diagnosis.', '{"source": "American Thyroid Association", "parameter": "TSH", "urgency_context": "Subclinical abnormalities require routine follow-up with physician"}'::jsonb),

('b0000009-0000-0000-0000-000000000006', 'a0000006-0000-0000-0000-000000000006', 1, 'Fasting Glucose & HbA1c',
'Fasting glucose represents acute glycemic status after an overnight fast, while HbA1c shows average blood sugar across 90 days. Levels between 100-125 mg/dL (fasting) or 5.7%-6.4% (HbA1c) reflect prediabetes, an important window for lifestyle modification including dietary improvements and exercise to prevent progression to type 2 diabetes.', '{"source": "American Diabetes Association", "parameter": "Glucose", "urgency_context": "Extremely high glucose (>300 mg/dL) with symptoms like confusion or nausea is an emergency"}'::jsonb),

('b0000010-0000-0000-0000-000000000007', 'a0000007-0000-0000-0000-000000000007', 1, 'Urinalysis Protein & Nitrites',
'Protein in urine (proteinuria) can be temporary due to dehydration, exercise, or fever, but persistent proteinuria is a marker of potential renal glomerulus stress. Nitrites and leukocyte esterase in urine strongly indicate bacterial presence in the urinary tract. Patients experiencing dysuria, flank pain, or fever should seek prompt medical evaluation for UTI.', '{"source": "NIH MedlinePlus", "parameter": "Urinalysis", "urgency_context": "Positive nitrites with fever or severe flank pain requires prompt medical evaluation"}'::jsonb)
ON CONFLICT (id) DO NOTHING;
